# -*- coding: utf-8 -*-
"""halo dunia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oBAwknCcZT2fmqMgdcpnoD1HYalGR_02
"""

print("Halo nama saya putri")